name: big-bear-gluetun
services:
  gluetun:
    cap_add:
      - NET_ADMIN
    cpu_shares: 90
    command: []
    container_name: gluetun
    deploy:
      resources:
        limits:
          memory: 15855M
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - OPENVPN_PASSWORD=AbUEkjTNd8BVm54AMqbhymaE
      - OPENVPN_USER=kbXwDHmg6wX3jiUN7CbXi84N
      - PGID=1000
      - PUID=1000
      - TZ=America/Chicago
      - UPDATER_PERIOD=24h
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=openvpn
    hostname: gluetun
    image: qmcgaw/gluetun:v3.40.0
    labels:
      icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/gluetun.png
    ports:
      - mode: ingress
        target: 8888
        published: "8888"
        protocol: tcp
      - mode: ingress
        target: 8388
        published: "8388"
        protocol: tcp
      - mode: ingress
        target: 8388
        published: "8388"
        protocol: udp
      - target: 8080
        published: "8080"
        protocol: tcp
      - target: 6881
        published: "6881"
        protocol: tcp
      - target: 6881
        published: "6881"
        protocol: udp
      - target: 9696
        published: "9696"
        protocol: tcp
      - target: 8989
        published: "8989"
        protocol: tcp
      - target: 7878
        published: "7878"
        protocol: tcp
      - target: 8191
        published: "8191"
        protocol: tcp
      - target: 5055
        published: "5055"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/gluetun
        target: /gluetun
        bind:
          create_host_path: true
    x-casaos:
      ports:
        - container: "8888"
          description:
            en_us: HTTP Proxy
        - container: "8388"
          description:
            en_us: Shadowsocks
      volumes:
        - container: /dev/net/tun
          description:
            en_us: Tun
    network_mode: bridge
    privileged: false
x-casaos:
  architectures:
    - amd64
    - arm64
  author: BigBearTechWorld
  category: BigBearCasaOS
  description:
    en_us: Lightweight swiss-knife-like VPN client to multiple VPN service providers
  developer: portainer
  hostname: ""
  icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/gluetun.png
  index: /
  is_uncontrolled: false
  main: gluetun
  port_map: ""
  scheme: http
  store_app_id: big-bear-gluetun
  tagline:
    en_us: Gluetun
  thumbnail: ""
  tips:
    before_install:
      en_us: >
        You will need to configure the providers in the environment variables.
        See: [BigBearCasaOS Gluetun
        Docs](https://community.bigbeartechworld.com/t/added-gluetun-to-big-bear-casaos/175)
  title:
    custom: ""
    en_us: Gluetun
