name: flaresolverr
services:
  flaresolverr:
    cpu_shares: 50
    command: []
    deploy:
      resources:
        limits:
          memory: 15855M
        reservations:
          memory: "67108864"
    environment:
      - CAPTCHA_SOLVER=none
      - LOG_HTML=false
      - LOG_LEVEL=info
      - PGID=1000
      - PUID=1000
      - TZ=America/Chicago
      - UMASK=002
    image: ghcr.io/flaresolverr/flaresolverr:v3.3.21
    labels:
      icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/FlareSolverr/icon.png
    restart: unless-stopped
    ports: []
    volumes: []
    devices: []
    cap_add: []
    network_mode: container:gluetun
    privileged: false
    container_name: ""
    hostname: ""
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  author: calganaygun
  category: Network
  hostname: ""
  icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/FlareSolverr/icon.png
  index: /
  is_uncontrolled: false
  port_map: "8191"
  scheme: http
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/FlareSolverr/screenshot-1.png
  store_app_id: flaresolverr
  title:
    custom: ""
    en_us: FlareSolverr
