name: nextcloud
services:
  cron:
    cpu_shares: 90
    command: []
    depends_on:
      db-nextcloud:
        condition: service_healthy
        required: true
      redis-nextcloud:
        condition: service_healthy
        required: true
    deploy:
      resources:
        limits:
          memory: 15855M
    entrypoint:
      - /cron.sh
    image: bigbeartechworld/big-bear-nextcloud-with-smbclient:0.0.5
    labels:
      icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/nextcloud.png
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/nextcloud/nextcloud/html  # NVMe for Nextcloud app files
        target: /var/www/html
        bind:
          create_host_path: true
    x-casaos:
      volumes:
        - container: /var/www/html
          description:
            en_us: "Container Path: /var/www/html"
    ports: []
    devices: []
    cap_add: []
    environment: []
    networks:
      - nextcloud_network
    privileged: false
    container_name: ""
    hostname: ""

  db-nextcloud:
    cpu_shares: 90
    command: []
    container_name: db-nextcloud
    deploy:
      resources:
        limits:
          memory: 15855M
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_PASSWORD=casaos
      - POSTGRES_USER=casaos
    hostname: db-nextcloud
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U casaos -d nextcloud
      timeout: 5s
      interval: 10s
      retries: 5
    image: postgres:14.2
    labels:
      icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/nextcloud.png
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/nextcloud/nextcloud/pgdata  # NVMe for PostgreSQL
        target: /var/lib/postgresql/data
        bind:
          create_host_path: true
    x-casaos:
      envs:
        - container: POSTGRES_PASSWORD
          description:
            en_us: Database password
        - container: POSTGRES_USER
          description:
            en_us: Database user
        - container: POSTGRES_DB
          description:
            en_us: Database type
      volumes:
        - container: /var/lib/postgresql/data
          description:
            en_us: "Container Path: /var/lib/postgresql/data"
    ports: []
    devices: []
    cap_add: []
    networks:
      - nextcloud_network
    privileged: false

  nextcloud:
    cpu_shares: 90
    command: []
    container_name: nextcloud
    depends_on:
      db-nextcloud:
        condition: service_healthy
        required: true
      redis-nextcloud:
        condition: service_healthy
        required: true
    deploy:
      resources:
        limits:
          memory: 15855M
    environment:
      - NEXTCLOUD_ADMIN_PASSWORD=casaos
      - NEXTCLOUD_ADMIN_USER=casaos
      - OVERWRITEPROTOCOL=http
      - PHP_MEMORY_LIMIT=1024M
      - PHP_UPLOAD_LIMIT=1024M
      - POSTGRES_DB=nextcloud
      - POSTGRES_HOST=db-nextcloud
      - POSTGRES_PASSWORD=casaos
      - POSTGRES_USER=casaos
      - REDIS_HOST=redis-nextcloud
      - TRUSTED_PROXIES=
    hostname: nextcloud
    image: bigbeartechworld/big-bear-nextcloud-with-smbclient:0.0.5
    labels:
      icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/nextcloud.png
    ports:
      - mode: ingress
        target: 80
        published: "7580"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/nextcloud/nextcloud/html  # NVMe for Nextcloud app files
        target: /var/www/html
        bind:
          create_host_path: true
      - type: bind
        source: /mnt/Wolf8tbHdd1/data/nextcloud/data  # HDD for user data, i.e. photos, docs, anything the user uploads
        target: /var/www/html/data
        bind:
          create_host_path: true
    x-casaos:
      envs:
        - container: POSTGRES_HOST
          description:
            en_us: Database host
        - container: REDIS_HOST
          description:
            en_us: Redis host
        - container: POSTGRES_PASSWORD
          description:
            en_us: Database password
        - container: POSTGRES_USER
          description:
            en_us: Database user
        - container: POSTGRES_DB
          description:
            en_us: Database type
        - container: NEXTCLOUD_ADMIN_USER
          description:
            en_us: Nextcloud admin user
        - container: NEXTCLOUD_ADMIN_PASSWORD
          description:
            en_us: Nextcloud admin password
        - container: TRUSTED_PROXIES
          description:
            en_us: Trusted proxies
        - container: OVERWRITEPROTOCOL
          description:
            en_us: Overwrite protocol
        - container: PHP_UPLOAD_LIMIT
          description:
            en_us: PHP upload limit
      ports:
        - container: "7580"
          description:
            en_us: "Container Port: 7580"
      volumes:
        - container: /var/www/html
          description:
            en_us: "Container Path: /var/www/html"
    devices: []
    cap_add: []
    networks:
      - nextcloud_network
    privileged: false

  redis-nextcloud:
    cpu_shares: 90
    command: []
    container_name: redis-nextcloud
    deploy:
      resources:
        limits:
          memory: 15855M
    hostname: redis-nextcloud
    healthcheck:
      test:
        - CMD-SHELL
        - redis-cli ping || exit 1
      timeout: 5s
      interval: 10s
      retries: 5
    image: redis:6.2.6
    labels:
      icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/nextcloud.png
    restart: unless-stopped
    user: 1000:1000
    volumes:
      - type: bind
        source: /DATA/AppData/nextcloud/nextcloud/redis  # NVMe for Redis
        target: /data
        bind:
          create_host_path: true
    x-casaos:
      ports:
        - container: "6379"
          description:
            en_us: "Container Port: 6379"
      volumes:
        - container: /data
          description:
            en_us: "Container Path: /data"
    ports: []
    devices: []
    cap_add: []
    environment: []
    networks:
      - nextcloud_network
    privileged: false

networks:
  nextcloud_network:
    name: big-bear-nextcloud_nextcloud_network
    driver: bridge

x-casaos:
  architectures:
    - amd64
    - arm64
  author: BigBearTechWorld
  category: BigBearCasaOS
  description:
    en_us: Nextcloud puts your data at your fingertips, under your control. Store
      your documents, calendar, contacts and photos on a server at home, at one
      of our providers or in a data center you trust.
  developer: nextcloud
  hostname: ""
  icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/nextcloud.png
  index: /
  is_uncontrolled: false
  main: nextcloud
  port_map: "7580"
  scheme: http
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Nextcloud/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Nextcloud/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Nextcloud/screenshot-3.png
  store_app_id: big-bear-nextcloud
  tagline:
    en_us: The productivity platform that keeps you in control
  thumbnail: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Nextcloud/thumbnail.jpg
  tips:
    before_install:
      en_us: >
        Read the [Nextcloud installation
        guide](https://community.bigbeartechworld.com/t/added-nextcloud-to-bigbearcasaos/455?u=dragonfire1119)
  title:
    custom: ""
    en_us: Nextcloud